steps:
  - label: ":pipeline: generate"
    agents:
      queue: linux-small
    env:
      BUILDKITE_GIT_DIFF_BASE: origin/main
      BUILDKITE_FETCH_DIFF_BASE: "true"
    command: |
      set -euo pipefail
      python3 .buildkite/generate_pipeline.py > .buildkite/generated-pipeline.yml
      buildkite-agent pipeline upload --dry-run < .buildkite/generated-pipeline.yml > /dev/null
      buildkite-agent artifact upload .buildkite/generated-pipeline.yml
      buildkite-agent pipeline upload --replace .buildkite/generated-pipeline.yml
